<?php
$lang = [
    'en' => [
        'logIn' => 'Log In',
        'register' => 'Register',
        'logOut' => 'Log Out',
        'name' => 'Name',
        'email' => 'Email',
        'validEmail' => 'Enter a valid email address!',
        'password' => 'Password',
        'repeatPassword' => 'Repeat password',
        'passError' => 'Passwords must match!',
        'min4characters' => 'Enter at least 4 Characters',
        'min5characters' => 'Enter at least 5 Characters',
        'max10characters' => 'Enter no more than 10 Characters',
        'agree' => 'I agree to the',
        'terms' => 'Terms and Conditions',
        'submit' => 'Send',
        'aboutUs' => 'Cronose is a project designed by four students of the IES Manacor Institute, Mallorca. <br><br> This project is part of the final validation of the top module of Web Application Development (DAW) as a fundamental piece in obtaining the necessary skills. <br><br>Cronose starts from the idea of creating an online time bank, a tool capable of connecting registered users on the platform to exchange favors or jobs with each other without paying for these services. Each user contributes their skills or knowledge to the rest of the community and to the same extent can use those offered by other users.'
        'myOffers' => 'My Offers'
        'market' => 'Market'
    ],
    'es' => [
        'logIn' => 'Inicia Sesión',
        'register' => 'Registrar',
        'logOut' => 'Cerrar Sesión',
        'name' => 'Nombre',
        'email' => 'Correo',
        'validEmail' => '¡Introduce un correo valido!',
        'password' => 'Contraseña',
        'repeatPassword' => 'Repite la contraseña',
        'passError' => '¡Las contraseñas deben coincidir!',
        'min4characters' => 'Ingrese al menos 4 caracteres',
        'min5characters' => 'Ingrese al menos 5 caracteres',
        'max10characters' => 'Ingrese menos de 10 caracteres',
        'agree' => 'Estoy de acuerdo con los',
        'terms' => 'términos y condiciones',
        'submit' => 'Enviar',
        'aboutUs' => 'Cronose es un proyecto diseñado por cuatro estudiantes del instituto IES Manacor, Mallorca. <br><br> Dicho proyecto forma parte de la validación final del módulo superior de Desarrollo de Aplicaciones Web (DAW) como pieza fundamental en la obtención de las aptitudes necesarias. <br><br> Cronose parte de la idea de crear un banco de tiempo online, una herramienta capaz de conectar a usuarios registrados en la plataforma para intercambiar favores o trabajos entre ellos sin necesidad de pagar por estos servicios. Cada usuario aporta sus habilidades o conocimientos al resto de comunidad y en la misma medida puede utilizar los que el resto de usuarios le ofrecen.'
        'myOffers' => 'Mis Ofertas'
        'market' => 'Mercado'
    ],
    'ca' => [
        'logIn' => 'Inicia Sessió',
        'register' => 'Registrar-se',
        'logOut' => 'Tancar Sessió',
        'name' => 'Nom',
        'email' => 'Correu',
        'validEmail' => 'Introdueix un correu valid!',
        'password' => 'Contrasenya',
        'repeatPassword' => 'Repetiu la contrsenya',
        'passError' => 'Les contrasenyes han de coincidir!',
        'min4characters' => 'Introduïu un mínim de 4 caràcters',
        'min5characters' => 'Introduïu un mínim de 5 caràcters',
        'max10characters' => 'Introduïu menys de 10 caràcters',
        'agree' => "Estic d'acord amb els",
        'terms' => 'Termes i Condicions',
        'submit' => 'Enviar',
        'aboutUs' => 'Cronose és un projecte dissenyat per quatre estudiants de l\'institut IES Manacor, Mallorca. <br><br> Dit projecte forma part de la validació final del mòdul superior de Desenvolupament d\'Aplicacions Web (DAW) com a peça fonamental en l\'obtenció de les aptituds necessàries.<br><br> Cronose parteix de la idea de crear un banc de temps en línia, una eina capaç de connectar a usuaris registrats a la plataforma per intercanviar favors o treballs entre ells sense necessitat de pagar per aquests serveis. Cada usuari aporta les seves habilitats o coneixements a la resta de comunitat i en la mateixa mesura pot utilitzar els que la resta d\'usuaris li ofereixen.'
        'myOffers' => 'Les meves Ofertes'
        'market' => 'Mercat'
    ]
];
